name: Deployment - terraform apply or destroy

on:
  workflow_dispatch:
    inputs:
        action_type:
            description: "Type of action you want to take (i.e. 'build' or 'destroy')"
            required: true

env:
   AWS_REGION: ap-southeast-2
   IAM_ROLE: "arn:aws:iam::663790350014:role/GitHubActions-BudgetAlertTool"
   TF_VERSION: 1.3.7
permissions: 
   id-token: write
   contents: read

jobs:
  deploy-budget-alerts:
    name: 'deploy-budget-alerts'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'build'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init
        env:
          TF_VAR_budget_name: ${{ secrets.BUDGET_NAME }}
          TF_VAR_budget_cost: ${{ secrets.BUDGET_COST }}
          TF_VAR_budget_unit: ${{ secrets.BUDGET_UNIT }}
          TF_VAR_time_unit: ${{ secrets.TIME_UNIT }}
          TF_VAR_email_address: ${{ secrets.EMAIL_ADDRESS }}
          TF_VAR_min_notification_threshold: ${{ secrets.MIN_NOTIFICATION_THRESHOLD }}
          TF_VAR_max_notification_threshold: ${{ secrets.MAX_NOTIFICATION_THRESHOLD }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
        env:
            TF_VAR_budget_name: ${{ secrets.BUDGET_NAME }}
            TF_VAR_budget_cost: ${{ secrets.BUDGET_COST }}
            TF_VAR_budget_unit: ${{ secrets.BUDGET_UNIT }}
            TF_VAR_time_unit: ${{ secrets.TIME_UNIT }}
            TF_VAR_email_address: ${{ secrets.EMAIL_ADDRESS }}
            TF_VAR_min_notification_threshold: ${{ secrets.MIN_NOTIFICATION_THRESHOLD }}
            TF_VAR_max_notification_threshold: ${{ secrets.MAX_NOTIFICATION_THRESHOLD }}
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: false
        env:
            TF_VAR_budget_name: ${{ secrets.BUDGET_NAME }}
            TF_VAR_budget_cost: ${{ secrets.BUDGET_COST }}
            TF_VAR_budget_unit: ${{ secrets.BUDGET_UNIT }}
            TF_VAR_time_unit: ${{ secrets.TIME_UNIT }}
            TF_VAR_email_address: ${{ secrets.EMAIL_ADDRESS }}
            TF_VAR_min_notification_threshold: ${{ secrets.MIN_NOTIFICATION_THRESHOLD }}
            TF_VAR_max_notification_threshold: ${{ secrets.MAX_NOTIFICATION_THRESHOLD }}
  
  destroy-budget-alerts:
    name: 'destroy-budget-alerts'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'destroy'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init
        env:
          TF_VAR_budget_name: ${{ secrets.BUDGET_NAME }}
          TF_VAR_budget_cost: ${{ secrets.BUDGET_COST }}
          TF_VAR_budget_unit: ${{ secrets.BUDGET_UNIT }}
          TF_VAR_time_unit: ${{ secrets.TIME_UNIT }}
          TF_VAR_email_address: ${{ secrets.EMAIL_ADDRESS }}
          TF_VAR_min_notification_threshold: ${{ secrets.MIN_NOTIFICATION_THRESHOLD }}
          TF_VAR_max_notification_threshold: ${{ secrets.MAX_NOTIFICATION_THRESHOLD }}

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
        env:
            TF_VAR_budget_name: ${{ secrets.BUDGET_NAME }}
            TF_VAR_budget_cost: ${{ secrets.BUDGET_COST }}
            TF_VAR_budget_unit: ${{ secrets.BUDGET_UNIT }}
            TF_VAR_time_unit: ${{ secrets.TIME_UNIT }}
            TF_VAR_email_address: ${{ secrets.EMAIL_ADDRESS }}
            TF_VAR_min_notification_threshold: ${{ secrets.MIN_NOTIFICATION_THRESHOLD }}
            TF_VAR_max_notification_threshold: ${{ secrets.MAX_NOTIFICATION_THRESHOLD }}
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        continue-on-error: false
        env:
            TF_VAR_budget_name: ${{ secrets.BUDGET_NAME }}
            TF_VAR_budget_cost: ${{ secrets.BUDGET_COST }}
            TF_VAR_budget_unit: ${{ secrets.BUDGET_UNIT }}
            TF_VAR_time_unit: ${{ secrets.TIME_UNIT }}
            TF_VAR_email_address: ${{ secrets.EMAIL_ADDRESS }}
            TF_VAR_min_notification_threshold: ${{ secrets.MIN_NOTIFICATION_THRESHOLD }}
            TF_VAR_max_notification_threshold: ${{ secrets.MAX_NOTIFICATION_THRESHOLD }}

